<template>
  <div class="content container">
    <h1>Privacy policy</h1>
    <h2>1. Data protection at a glance</h2>
    <h3>General notes</h3> <p>The following information provides a simple overview of what happens to your personal data when you visit this website. Personal data is all data with which you can be personally identified. For detailed information on the subject of data protection, please refer to our data protection declaration listed below this text.</p>
    <h3>Data collection on this website</h3>
    <p><strong>Who is responsible for data collection on this website?</strong></p>
    <p>The data processing on this website is carried out by the website operator. You can find his contact details in the imprint of this website.</p>
    <p><strong>How do we collect your data?</strong>
    </p> <p>On the one hand, your data is collected when you provide it to us. This may be data that you enter in a contact form, for example.</p>
    <p>Other data is collected automatically or with your consent by our IT systems when you visit the website. These are mainly technical data (e.g. Internet browser, operating system or time of the page call). This data is collected automatically as soon as you enter this website.</p>
    <p><strong>What do we use your data for?</strong></p>
    <p>Part of the data is collected to ensure that the website is provided without errors. Other data can be used to analyse your user behaviour.</p>
    <p><strong>What rights do you have regarding your data?</strong></p>
    <p>You have the right to receive information free of charge at any time about the origin, recipient and purpose of your stored personal data. You also have the right to demand the correction or deletion of this data. If you have given your consent to data processing, you can revoke this consent at any time for the future. In addition, you have the right to request, under certain circumstances, the restriction of the processing of your personal data. Furthermore, you have the right of appeal to the competent supervisory authority.</p>
    <p>You can contact us at any time at the address given in the imprint for this and other questions on the subject of data protection.</p>
    <h2>2. Hosting and content delivery networks (CDN)</h2>
    <h3>External Hosting</h3>
    <p>This website is hosted by an external service provider (Hoster). The personal data collected on this website is stored on the hoster's servers. This may include, but is not limited to, IP addresses, contact requests, meta and communication data, contract data, contact details, names, website accesses and other data generated by a website.</p>
    <p>The use of the hoster is for the purpose of fulfilling a contract with our potential and existing customers (Art. 6 para. 1 lit. b DSGVO) and in the interest of a secure, fast and efficient provision of our online offer by a professional provider (Art. 6 para. 1 lit. f DSGVO).</p>
    <p>Our hoster will only process your data to the extent necessary to fulfil its performance obligations and will follow our instructions with regard to this data.</p>
    <h2>3. General instructions and compulsory information</h2>
    <h3>Data protection</h3>
    <p>The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and according to the legal data protection regulations as well as this privacy policy.</p>
    <p>When you use this website, various personal data is collected. Personal data is data with which you can be personally identified. This privacy policy explains what data we collect and what we use it for. It also explains how and for what purpose this is done.</p>
    <p>We would like to point out that data transmission on the Internet (e.g. communication by e-mail) can have security gaps. A complete protection of data against access by third parties is not possible.</p>
    <h3>Note on the responsible body</h3>
    <p>The person responsible for data processing on this website is:</p>
    <p>Timon Christiansen<br />
      Storkower Str. 205a, Apartment 8<br />
      10369, Berlin</p>

    <p>Phone: +491731527561<br />
      E-Mail: timon.christiansen@code.berlin</p>
    <p>The controller is the natural or legal person who alone or jointly with others determines the purposes and means of the processing of personal data (e.g. names, e-mail addresses, etc.).</p>
    <h3>Revocation of your consent to data processing</h3>
    <p>Many data processing operations are only possible with your express consent. You can revoke a previously given consent at any time. For this purpose an informal notification by e-mail to us is sufficient. The legality of the data processing carried out up to the time of revocation remains unaffected by the revocation.</p>
    <h3>Right to object to data collection in special cases and to direct advertising (Art. 21 DSGVO)</h3>
    <p>IF THE DATA PROCESSING IS CARRIED OUT ON THE BASIS OF ART. 6 ABS. 1 LIT. E OR F DSGVO, YOU SHALL HAVE THE RIGHT TO OBJECT TO THE PROCESSING OF YOUR PERSONAL DATA AT ANY TIME FOR REASONS ARISING FROM YOUR SPECIFIC SITUATION, INCLUDING PROFILING BASED ON THESE PROVISIONS. THE RESPECTIVE LEGAL BASIS ON WHICH PROCESSING IS BASED CAN BE FOUND IN THIS PRIVACY STATEMENT. IF YOU OBJECT, WE WILL NO LONGER PROCESS YOUR PERSONAL DATA CONCERNED, UNLESS WE CAN PROVE THAT THERE ARE COMPELLING REASONS FOR PROCESSING WHICH ARE WORTHY OF PROTECTION AND WHICH OUTWEIGH YOUR INTERESTS, RIGHTS AND FREEDOMS, OR IF THE PROCESSING SERVES TO ASSERT, EXERCISE OR DEFEND LEGAL CLAIMS (OBJECTION ACCORDING TO ART. 21 PARA. 1 DSGVO).</p>
    <p>IF YOUR PERSONAL DATA ARE PROCESSED FOR THE PURPOSE OF DIRECT MARKETING, YOU HAVE THE RIGHT TO OBJECT AT ANY TIME TO THE PROCESSING OF PERSONAL DATA CONCERNING YOU FOR THE PURPOSE OF SUCH MARKETING, INCLUDING PROFILING, INSOFAR AS IT IS CONNECTED WITH SUCH DIRECT MARKETING. IF YOU OBJECT, YOUR PERSONAL DATA WILL SUBSEQUENTLY NO LONGER BE USED FOR THE PURPOSE OF DIRECT MARKETING (OBJECTION ACCORDING TO ARTICLE 21 PARAGRAPH 2 DSGVO).</p>
    <h3>Right of appeal to the competent supervisory authority</h3>
    <p>In the event of infringements of the DSGVO, those concerned have a right of appeal to a supervisory authority, in particular in the Member State of their habitual residence, place of work or the place where the alleged infringement was committed. This right of appeal is without prejudice to other administrative or judicial remedies.</p>
    <h3>Right to data portability</h3>
    <p>You have the right to have data which we process automatically on the basis of your consent or in fulfilment of a contract handed over to you or to a third party in a common, machine-readable format. If you request the direct transfer of the data to another responsible party, this will only take place to the extent that it is technically feasible.</p>
    <h3>SSL or TLS Encryption</h3>
    <p>This site uses SSL or TLS encryption for security reasons and to protect the transmission of confidential content, such as orders or inquiries that you send to us as site operator. You can recognize an encrypted connection by the fact that the address line of the browser changes from "http://" to "https://" and by the lock symbol in your browser line.</p>
    <p>If SSL or TLS encryption is activated, the data you transmit to us cannot be read by third parties.</p>
    <h3>Information, deletion and correction</h3>
    <p>Within the framework of the applicable legal provisions, you have the right to obtain information free of charge at any time about your stored personal data, its origin and recipients and the purpose of the data processing and, if applicable, a right to correct or delete this data. For this purpose, as well as for further questions regarding personal data, you can contact us at any time at the address given in the imprint.</p>
    <h3>Right to limitation of processing</h3>
    <p>You have the right to request the restriction of the processing of your personal data. To do so, you can contact us at any time at the address given in the imprint. The right to restrict processing exists in the following cases:</p>
    <ul>
      <li>If you dispute the accuracy of your personal data stored with us, we usually need time to verify this. For the duration of the review, you have the right to demand the restriction of the processing of your personal data.</li>
      <li>If the processing of your personal data was/is unlawful, you may request the restriction of data processing instead of deletion.</li>
      <li>If we no longer need your personal data, but you need them in order to exercise, defend or assert legal claims, you have the right to request restriction of the processing of your personal data instead of deletion.</li>
      <li>If you have lodged an objection in accordance with Art. 21 Paragraph 1 DSGVO, a balance must be struck between your interests and ours. As long as it has not yet been determined whose interests outweigh the interests of both parties, you have the right to demand that the processing of your personal data be restricted.</li>
    </ul>
    <p>If you have restricted the processing of your personal data, these data - apart from their storage - may only be processed with your consent or for the assertion, exercise or defence of legal claims or for the protection of the rights of another natural or legal person or for reasons of an important public interest of the European Union or a Member State.</p>
    <h2>4. Data collection on this website</h2>
    <h3>Inquiry by e-mail, telephone or fax</h3>
    <p>If you contact us by e-mail, telephone or fax, your inquiry including all personal data (name, inquiry) will be stored and processed by us for the purpose of processing your request. We will not pass on this data without your consent.</p>
    <p>The processing of this data is carried out on the basis of Art. 6 para. 1 lit. b DSGVO, insofar as your enquiry is connected with the fulfilment of a contract or is necessary for the implementation of pre-contractual measures. In all other cases, the processing is based on our legitimate interest in the effective processing of the enquiries addressed to us (Art. 6 para. 1 lit. f DSGVO) or on your consent (Art. 6 para. 1 lit. a DSGVO), provided that this has been requested</p>
    <p>The data sent to us by you via contact enquiries will remain with us until you request us to delete it, revoke your consent to its storage or the purpose for which it was stored ceases to apply (e.g. after your request has been processed). Mandatory statutory provisions - in particular statutory retention periods - remain unaffected.</p>
    <h2>5. Plugins and Tools</h2>
    <h3>Google Web Fonts</h3>
    <p>This page uses so-called web fonts, which are provided by Google, for the uniform display of fonts. When you call up a page, your browser loads the required web fonts into its browser cache to display text and fonts correctly.</p>
    <p>To do this, the browser you are using must connect to Google's servers. This enables Google to know that this website has been accessed via your IP address. The use of Google WebFonts is based on Art. 6 para. 1 lit. f DSGVO. The website operator has a legitimate interest in the uniform presentation of the font on his website. If a corresponding consent has been requested (e.g. consent to the storage of cookies), the processing is carried out exclusively on the basis of Art. 6 para. 1 lit. a DSGVO; the consent can be revoked at any time.</p>
    <p>If your browser does not support web fonts, a standard font is used by your computer.</p>
    <p>Further information on Google Web Fonts can be found at <a href="https://developers.google.com/fonts/faq" target="_blank" rel="noopener noreferrer">https://developers.google.com/fonts/faq</a> and in the Google privacy policy: <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy?hl=de</a>.</p>
    <h3>Spotify</h3>
    <p>On this website functions of the music service Spotify are integrated. The provider is Spotify AB, Birger Jarlsgatan 61, 113 56 Stockholm, Sweden. You can recognize the Spotify plugins by the green logo on this website. An overview of the Spotify plugins can be found at: <a href="https://developer.spotify.com" target="_blank" rel="noopener noreferrer">https://developer.spotify.com</a>.</p>
    <p>This allows a direct connection between your browser and the Spotify server when you visit this website via the plugin. Spotify will then receive information that you have visited this website with your IP address. If you click on the Spotify button while you are logged in to your Spotify account, you can link the content of this website on your Spotify profile. This allows Spotify to associate your visit to this website with your account.</p>
    <p>The storage and analysis of the data is based on Art. 6 para. 1 lit. f DSGVO. The website operator has a legitimate interest in the attractive acoustic design of his website. If a corresponding consent has been requested (e.g. consent to the storage of cookies), the processing is carried out exclusively on the basis of Art. 6 para. 1 lit. a DSGVO; the consent can be revoked at any time.</p>
    <p>For further information, please refer to the Spotify privacy policy: <a href="https://www.spotify.com/de/legal/privacy-policy/" target="_blank" rel="noopener noreferrer">https://www.spotify.com/de/legal/privacy-policy/</a>.</p>
    <p>If you do not want Spotify to associate your visit to this website with your Spotify account, please log out of your Spotify account.</p>
    <br>
    <p>Source: <a href="https://www.e-recht24.de">eRecht24</a></p>
  </div>
</template>

<script>
  export default {
    name: 'privacy'
  }
</script>

<style scoped>
  .container {
    text-align: left;
    display: block;
  }
  h1 {
    display: block;
    font-size: 2em;
    text-align: center;
    margin-block-start: 0.67em;
    margin-block-end: 0.67em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    font-weight: bold;
  }
  h2 {
    display: block;
    font-size: 1.5em;
    margin-block-start: 0.83em;
    margin-block-end: 0.83em;
    margin-inline-start: 0;
    margin-inline-end: 0;
    font-weight: bold;
  }
  h3 {
    display: block;
    font-size: 1.17em;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0;
    margin-inline-end: 0;
    font-weight: bold;
    text-align: left;
  }
  @media (max-width: 640px) {
    p {
      @apply px-4
    }
  }

  @media (min-width: 640px) {
    .container {
      max-width: 800px;
    }
  }
</style>
